import type { ThemeConfig } from "antd";

export const platformTheme: ThemeConfig = {
  cssVar: { prefix: "a2a" },
  hashed: true,
  token: {
    // Quiet graphite workspace: ink is the primary action color and semantic
    // tones stay muted so status never competes with the conversation.
    colorPrimary: "#212121",
    colorPrimaryHover: "#303030",
    colorPrimaryActive: "#252525",
    colorSuccess: "#18794e",
    colorWarning: "#8a6116",
    colorError: "#a43e45",
    colorInfo: "#43607c",
    colorText: "#212121",
    colorTextSecondary: "#626262",
    colorTextTertiary: "#858585",
    colorTextDisabled: "#ababab",
    colorBorder: "#d8d8d8",
    colorBorderSecondary: "#e7e7e7",
    colorBgLayout: "#f7f7f7",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorFill: "#eeeeee",
    colorFillSecondary: "#f2f2f2",
    colorFillTertiary: "#f6f6f6",
    colorFillQuaternary: "#fafafa",
    borderRadius: 8,
    borderRadiusSM: 6,
    borderRadiusLG: 10,
    borderRadiusOuter: 12,
    controlHeight: 36,
    controlHeightSM: 32,
    controlHeightLG: 40,
    fontSize: 13,
    fontSizeSM: 12,
    fontSizeLG: 14,
    lineHeight: 1.55,
    fontFamily:
      "'Segoe UI Variable Text', 'Segoe UI', 'PingFang SC', 'Noto Sans CJK SC', 'Microsoft YaHei', ui-sans-serif, system-ui, sans-serif",
    boxShadow: "0 3px 10px rgb(0 0 0 / 0.07)",
    boxShadowSecondary: "0 18px 46px rgb(0 0 0 / 0.13)",
    motionDurationFast: "0.12s",
    motionDurationMid: "0.16s",
    motionEaseInOut: "cubic-bezier(0.2, 0, 0, 1)",
  },
  components: {
    Button: {
      fontWeight: 600,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultBorderColor: "#d8d8d8",
      defaultColor: "#3f3f3f",
      defaultHoverBg: "#f5f5f5",
      defaultHoverBorderColor: "#bcbcbc",
      defaultHoverColor: "#212121",
      defaultActiveBg: "#ebebeb",
      defaultActiveBorderColor: "#a8a8a8",
      defaultActiveColor: "#111111",
      textHoverBg: "#eeeeee",
    },
    Card: {
      headerFontSize: 14,
      paddingLG: 18,
      colorBorderSecondary: "#e3e3e3",
      boxShadowTertiary: "none",
    },
    Checkbox: { colorPrimaryHover: "#212121" },
    Collapse: {
      headerBg: "#ffffff",
      contentBg: "#ffffff",
    },
    Drawer: { paddingLG: 20 },
    Dropdown: { paddingBlock: 5 },
    Input: {
      hoverBorderColor: "#bcbcbc",
      activeBorderColor: "#777777",
      activeShadow: "0 0 0 2px rgb(93 93 93 / 0.14)",
      errorActiveShadow: "0 0 0 2px rgb(164 62 69 / 0.12)",
    },
    InputNumber: {
      hoverBorderColor: "#bcbcbc",
      activeBorderColor: "#777777",
      activeShadow: "0 0 0 2px rgb(93 93 93 / 0.14)",
    },
    Menu: {
      itemHeight: 38,
      itemBorderRadius: 7,
      itemMarginInline: 0,
      itemSelectedBg: "#e8e8e8",
      itemSelectedColor: "#171717",
      itemColor: "#4a4a4a",
      itemHoverBg: "#ededed",
      itemHoverColor: "#171717",
    },
    Modal: { borderRadiusLG: 12, paddingContentHorizontalLG: 22 },
    Pagination: { itemActiveBg: "#eeeeee" },
    Segmented: {
      itemHoverBg: "#f1f1f1",
      itemHoverColor: "#171717",
      itemSelectedBg: "#ffffff",
    },
    Select: {
      hoverBorderColor: "#bcbcbc",
      activeBorderColor: "#777777",
      activeOutlineColor: "rgb(93 93 93 / 0.14)",
      optionActiveBg: "#ededed",
      optionSelectedBg: "#e8e8e8",
    },
    Table: {
      headerBg: "#f7f7f7",
      headerColor: "#626262",
      headerSplitColor: "transparent",
      rowHoverBg: "#f6f6f6",
      cellPaddingBlockSM: 10,
      cellPaddingInlineSM: 10,
    },
    Tabs: {
      itemHoverColor: "#171717",
      itemSelectedColor: "#171717",
      inkBarColor: "#171717",
      titleFontSize: 12,
    },
    Tag: {
      borderRadiusSM: 5,
      defaultBg: "#f0f0f0",
      defaultColor: "#5d5d5d",
    },
    Tooltip: {
      colorBgSpotlight: "#ffffff",
      colorTextLightSolid: "#343434",
    },
  },
};
