import type { ThemeConfig } from "antd";

export const platformTheme: ThemeConfig = {
  cssVar: { prefix: "a2a" },
  hashed: true,
  token: {
    // Quiet graphite workspace: ink is the primary action color and semantic
    // tones stay muted so status never competes with the conversation.
    colorPrimary: "#292925",
    colorPrimaryHover: "#3a3a35",
    colorPrimaryActive: "#1f1f1c",
    colorSuccess: "#1d7350",
    colorWarning: "#8a5c12",
    colorError: "#aa3c43",
    colorInfo: "#365f86",
    colorText: "#292925",
    colorTextSecondary: "#5f5f58",
    colorTextTertiary: "#76766f",
    colorTextDisabled: "#9a9a93",
    colorBorder: "#cdcdc5",
    colorBorderSecondary: "#dfdfd9",
    colorBgLayout: "#f4f4f2",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorFill: "#ecece8",
    colorFillSecondary: "#f1f1ed",
    colorFillTertiary: "#f7f7f4",
    colorFillQuaternary: "#fbfbf8",
    borderRadius: 8,
    borderRadiusSM: 6,
    borderRadiusLG: 12,
    borderRadiusOuter: 16,
    controlHeight: 36,
    controlHeightSM: 32,
    controlHeightLG: 40,
    fontSize: 13,
    fontSizeSM: 12,
    fontSizeLG: 14,
    lineHeight: 1.55,
    fontFamily:
      "'Segoe UI Variable Text', 'Segoe UI', 'PingFang SC', 'Noto Sans CJK SC', 'Microsoft YaHei', ui-sans-serif, system-ui, sans-serif",
    boxShadow: "0 3px 10px rgb(0 0 0 / 0.07)",
    boxShadowSecondary: "0 18px 46px rgb(0 0 0 / 0.13)",
    motionDurationFast: "0.12s",
    motionDurationMid: "0.16s",
    motionEaseInOut: "cubic-bezier(0.2, 0, 0, 1)",
  },
  components: {
    Button: {
      fontWeight: 600,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultBorderColor: "#cdcdc5",
      defaultColor: "#3f3f3f",
      defaultHoverBg: "#f0f0eb",
      defaultHoverBorderColor: "#aaa9a0",
      defaultHoverColor: "#292925",
      defaultActiveBg: "#e8e8e2",
      defaultActiveBorderColor: "#9f9f97",
      defaultActiveColor: "#111111",
      textHoverBg: "#ecece8",
    },
    Card: {
      headerFontSize: 14,
      paddingLG: 20,
      colorBorderSecondary: "#ddddd7",
      boxShadowTertiary: "none",
    },
    Checkbox: { colorPrimaryHover: "#292925" },
    Collapse: {
      headerBg: "#ffffff",
      contentBg: "#ffffff",
    },
    Drawer: { paddingLG: 20 },
    Dropdown: { paddingBlock: 5 },
    Input: {
      hoverBorderColor: "#aaa9a0",
      activeBorderColor: "#73736c",
      activeShadow: "0 0 0 2px rgb(54 95 134 / 0.18)",
      errorActiveShadow: "0 0 0 2px rgb(170 60 67 / 0.14)",
    },
    InputNumber: {
      hoverBorderColor: "#aaa9a0",
      activeBorderColor: "#73736c",
      activeShadow: "0 0 0 2px rgb(54 95 134 / 0.18)",
    },
    Menu: {
      itemHeight: 38,
      itemBorderRadius: 7,
      itemMarginInline: 0,
      itemSelectedBg: "#deded8",
      itemSelectedColor: "#1f1f1c",
      itemColor: "#4f4f49",
      itemHoverBg: "#e5e5df",
      itemHoverColor: "#1f1f1c",
    },
    Modal: { borderRadiusLG: 16, paddingContentHorizontalLG: 24 },
    Pagination: { itemActiveBg: "#ecece8" },
    Segmented: {
      itemHoverBg: "#f1f1ed",
      itemHoverColor: "#1f1f1c",
      itemSelectedBg: "#ffffff",
    },
    Select: {
      hoverBorderColor: "#aaa9a0",
      activeBorderColor: "#73736c",
      activeOutlineColor: "rgb(54 95 134 / 0.18)",
      optionActiveBg: "#e5e5df",
      optionSelectedBg: "#deded8",
    },
    Table: {
      headerBg: "#f4f4f2",
      headerColor: "#5f5f58",
      headerSplitColor: "transparent",
      rowHoverBg: "#f7f7f4",
      cellPaddingBlockSM: 10,
      cellPaddingInlineSM: 10,
    },
    Tabs: {
      itemHoverColor: "#1f1f1c",
      itemSelectedColor: "#1f1f1c",
      inkBarColor: "#1f1f1c",
      titleFontSize: 12,
    },
    Tag: {
      borderRadiusSM: 5,
      defaultBg: "#efefe9",
      defaultColor: "#5f5f58",
    },
    Tooltip: {
      colorBgSpotlight: "#ffffff",
      colorTextLightSolid: "#343434",
    },
  },
};
