import type { ThemeConfig } from "antd";

export const platformTheme: ThemeConfig = {
  cssVar: { prefix: "a2a" },
  hashed: true,
  token: {
    // Neutral white workspace: graphite is reserved for primary actions and
    // semantic tones stay quiet enough to preserve the reading hierarchy.
    colorPrimary: "#212121",
    colorPrimaryHover: "#2f2f2f",
    colorPrimaryActive: "#0d0d0d",
    colorSuccess: "#1d7350",
    colorWarning: "#8a5c12",
    colorError: "#aa3c43",
    colorInfo: "#365f86",
    colorText: "#0d0d0d",
    colorTextSecondary: "#676767",
    colorTextTertiary: "#8f8f8f",
    colorTextDisabled: "#b4b4b4",
    colorBorder: "#d9d9d9",
    colorBorderSecondary: "#e5e5e5",
    colorBgLayout: "#ffffff",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorFill: "#ececec",
    colorFillSecondary: "#f3f3f3",
    colorFillTertiary: "#f7f7f7",
    colorFillQuaternary: "#fafafa",
    borderRadius: 8,
    borderRadiusSM: 4,
    borderRadiusLG: 12,
    borderRadiusOuter: 12,
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 44,
    fontSize: 13,
    fontSizeSM: 12,
    fontSizeLG: 14,
    lineHeight: 1.55,
    fontFamily:
      "'Segoe UI Variable Text', 'Segoe UI', 'PingFang SC', 'Noto Sans CJK SC', 'Microsoft YaHei', ui-sans-serif, system-ui, sans-serif",
    boxShadow: "0 4px 14px rgb(0 0 0 / 0.08)",
    boxShadowSecondary: "0 16px 44px rgb(0 0 0 / 0.12)",
    motionDurationFast: "0.12s",
    motionDurationMid: "0.16s",
    motionEaseInOut: "cubic-bezier(0.2, 0, 0, 1)",
  },
  components: {
    Button: {
      fontWeight: 600,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultBorderColor: "#d9d9d9",
      defaultColor: "#2f2f2f",
      defaultHoverBg: "#f3f3f3",
      defaultHoverBorderColor: "#b4b4b4",
      defaultHoverColor: "#0d0d0d",
      defaultActiveBg: "#e8e8e8",
      defaultActiveBorderColor: "#a8a8a8",
      defaultActiveColor: "#0d0d0d",
      textHoverBg: "#ececec",
    },
    Card: {
      headerFontSize: 14,
      paddingLG: 20,
      colorBorderSecondary: "#ececec",
      boxShadowTertiary: "none",
    },
    Checkbox: { colorPrimaryHover: "#212121" },
    Collapse: {
      headerBg: "#ffffff",
      contentBg: "#ffffff",
    },
    Drawer: { paddingLG: 20 },
    Dropdown: { paddingBlock: 5 },
    Input: {
      hoverBorderColor: "#b4b4b4",
      activeBorderColor: "#0d0d0d",
      activeShadow: "0 0 0 2px rgb(13 13 13 / 0.16)",
      errorActiveShadow: "0 0 0 2px rgb(170 60 67 / 0.14)",
    },
    InputNumber: {
      hoverBorderColor: "#b4b4b4",
      activeBorderColor: "#0d0d0d",
      activeShadow: "0 0 0 2px rgb(13 13 13 / 0.16)",
    },
    Menu: {
      itemHeight: 40,
      itemBorderRadius: 8,
      itemMarginInline: 0,
      itemSelectedBg: "#e8e8e8",
      itemSelectedColor: "#0d0d0d",
      itemColor: "#676767",
      itemHoverBg: "#ececec",
      itemHoverColor: "#0d0d0d",
    },
    Modal: { borderRadiusLG: 12, paddingContentHorizontalLG: 24 },
    Pagination: { itemActiveBg: "#ececec" },
    Segmented: {
      itemHoverBg: "#f3f3f3",
      itemHoverColor: "#0d0d0d",
      itemSelectedBg: "#ffffff",
    },
    Select: {
      hoverBorderColor: "#b4b4b4",
      activeBorderColor: "#0d0d0d",
      activeOutlineColor: "rgb(13 13 13 / 0.16)",
      optionActiveBg: "#ececec",
      optionSelectedBg: "#e8e8e8",
    },
    Table: {
      headerBg: "#f7f7f7",
      headerColor: "#676767",
      headerSplitColor: "transparent",
      rowHoverBg: "#f7f7f7",
      cellPaddingBlockSM: 10,
      cellPaddingInlineSM: 10,
    },
    Tabs: {
      itemHoverColor: "#0d0d0d",
      itemSelectedColor: "#0d0d0d",
      inkBarColor: "#0d0d0d",
      titleFontSize: 12,
    },
    Tag: {
      borderRadiusSM: 4,
      defaultBg: "#f3f3f3",
      defaultColor: "#676767",
    },
    Tooltip: {
      colorBgSpotlight: "#212121",
      colorTextLightSolid: "#ffffff",
    },
  },
};
